export const EGYPT_GOVERNORATES = [
  { id: "cairo", nameAr: "القاهرة", nameEn: "Cairo" },
  { id: "giza", nameAr: "الجيزة", nameEn: "Giza" },
  { id: "alexandria", nameAr: "الإسكندرية", nameEn: "Alexandria" },
  { id: "dakahlia", nameAr: "الدقهلية", nameEn: "Dakahlia" },
  { id: "red_sea", nameAr: "البحر الأحمر", nameEn: "Red Sea" },
  { id: "beheira", nameAr: "البحيرة", nameEn: "Beheira" },
  { id: "fayoum", nameAr: "الفيوم", nameEn: "Fayoum" },
  { id: "gharbia", nameAr: "الغربية", nameEn: "Gharbia" },
  { id: "ismailia", nameAr: "الإسماعيلية", nameEn: "Ismailia" },
  { id: "monufia", nameAr: "المنوفية", nameEn: "Monufia" },
  { id: "minya", nameAr: "المنيا", nameEn: "Minya" },
  { id: "qalyubia", nameAr: "القليوبية", nameEn: "Qalyubia" },
  { id: "new_valley", nameAr: "الوادي الجديد", nameEn: "New Valley" },
  { id: "sharkia", nameAr: "الشرقية", nameEn: "Sharkia" },
  { id: "suez", nameAr: "السويس", nameEn: "Suez" },
  { id: "aswan", nameAr: "أسوان", nameEn: "Aswan" },
  { id: "assiut", nameAr: "أسيوط", nameEn: "Assiut" },
  { id: "beni_suef", nameAr: "بني سويف", nameEn: "Beni Suef" },
  { id: "portsaid", nameAr: "بورسعيد", nameEn: "Port Said" },
  { id: "damietta", nameAr: "دمياط", nameEn: "Damietta" },
  { id: "south_sinai", nameAr: "جنوب سيناء", nameEn: "South Sinai" },
  { id: "kafr_el_sheikh", nameAr: "كفر الشيخ", nameEn: "Kafr El Sheikh" },
  { id: "matrouh", nameAr: "مطروح", nameEn: "Matrouh" },
  { id: "luxor", nameAr: "الأقصر", nameEn: "Luxor" },
  { id: "qena", nameAr: "قنا", nameEn: "Qena" },
  { id: "north_sinai", nameAr: "شمال سيناء", nameEn: "North Sinai" },
  { id: "sohag", nameAr: "سوهاج", nameEn: "Sohag" },
] as const;

export type Governorate = (typeof EGYPT_GOVERNORATES)[number];
